### PR TITLE
Fix dual-monitor support on Linux

### PR DESCRIPTION
**Pull request by larsiusprime**
Fixes this issue in OpenFL: https://github.com/openfl/lime/issues/667

### CODE REVIEW

**Comment by underscorediscovery** [comment]
@jgranick @larsiusprime did nobody read this discussion here?

https://github.com/randomnine/sdl/pull/1

**Comment by underscorediscovery** [comment]
anyone?

**Comment by larsiusprime** [comment]
No, I didn't see that.

So you want to hide these all behind a define that's turned on in the framework itself?

**Comment by underscorediscovery** [comment]
I've elaborated in that thread but yea! Having tertiary build dependencies tacked on just to use the lib is not something that fits the model we're going for here.

**Comment by larsiusprime** [comment]
How many defines, 1 or multiple? Just give me some marching orders here and I'll clean it up.

**Comment by larsiusprime** [comment]
Also, added myself to the watch list here, I think that's why I didn't see your note before.

**Comment by underscorediscovery** [comment]
Sure! 
Note the existing native toolkit defines right on the lines below:

`SDL_VIDEO_DRIVER_X11_XINPUT2 NATIVE_TOOLKIT_SDL_X11_XINPUT2`

In this case, the build xml / framework specifies "I want to build with xinput2", and the dependency is added. This way, all existing users of the library aren't thrown to the wolves every week someone wants a new dependency, and they're opt in, not opt out - that's all it is :)

The same would be applied to the **two** new dependency changes, in the same way. 
That should be a a quick search and copy paste edit to add them - one for each - from what I understand the actual lib names aren't a problem being defined, just the one with the 1 or 0.

The framework can then further collate flags as needed, and define it by default, which would subsequently define the two native toolkit defines as needed.

Let me know if that helps

**Comment by larsiusprime** [comment]
Like this?

https://github.com/native-toolkit/sdl/compare/master...larsiusprime:master

My understanding is any define is FALSE by default, but to be sure, do I have to explicitly define these somewhere in SDL as false, and then in the external framework make sure to flip them to true?

**Pull request merged**
