### PR TITLE
(Re)Add NATIVE_TOOLKIT_STATIC_ANGLE switch to allow the angle library to be statically linked

### PR DESCRIPTION
**Pull request by madrazo**
Restablish
https://github.com/native-toolkit/sdl/commit/a78c07dc1f85019261f13ebc3177cb1b144c98e4
on newer SDL version

### CODE REVIEW

**Comment by underscorediscovery** [comment]
This seems like a patch for SDL @hughsando, why are we modifying the lib code directly? What platform needs this?

**Comment by madrazo** [comment]
@underscorediscovery @hughsando @jgranick It seems to be a good contribution to SDL since you can get rid of the DLLs.  I think that this only works with "Visual Studio 2015 Update 3"+? Anyway, I can send them the patch through their bugzilla if there are no objections (with a different flag name, SDL_VIDEO__STATIC_ANGLE?). It would take a long time to get to the official release.  

For winrt it is very convenient since you can be sure that everything is compiled using your Windows SDK version. I got winrt working on NME and I would be glad to see it working on Lime, Snow and others as well. Thanks 😄

**Comment by underscorediscovery** [comment]
I think sending it to SDL in their normal process is a good idea either way (including maybe the note about the motivation/reason). We definitely (as a general rule) try not to modify the libraries that native-toolkit provides easy access to.

Also since we use tags for versioning here, we often can and do use hg revisions of SDL, so as soon as they have it in tree it could be available here without much trouble.

**Comment by hughsando** [comment]
So what is the decision here? Wait for SDL?
Maybe we should create a "static-angle" branch which can disappear when we get upstream support.

**Comment by hughsando** [comment]
I have added this to a "nme" branch, and updated the nme-toolkit sub-modules to point to this, so if you update that repo, you should get the latest versions.
I'm re-working my build-servers at the moment, but I will get a haxelib release soon.

**Comment by madrazo** [comment]
@hughsando  As you can see from the mirror bots, this was added by Sam (the name of the flag is SDL_VIDEO_STATIC_ANGLE)

**Comment by hughsando** [comment]
I guess this means I should switch the nme-toolkit submodule back to the master branch soon.

**Comment by madrazo** [comment]
I just noticed that the official SDL 2.0.6 release included this flag (SDL_VIDEO_STATIC_ANGLE)

**Pull request closed without merging**
